import type { KeywordDef } from './types.ts'

export const HEADLINE = '🚨 IS IT DONE YET? 🚨'

// ── TIER 1: NAGS (large) ── Universal workplace nagging. Everyone gets these. ──
const nags: string[] = [
  'ETA?', 'status?', 'any updates?', 'is this done?',
  'who owns this?', 'per my last email', 'just checking in',
  'circling back', 'bumping this', 'gentle reminder',
  'friendly nudge', 'quick follow-up', 'let\'s circle back',
  'can we get an update?', 'where are we on this?',
  'are we on track?', 'this is urgent', 'need this ASAP',
  'please advise', 'when can we expect this?',
  'can you hop on a call?', 'let\'s sync',
  'did you see my message?', 'did you get my email?',
  'following up on my follow-up', 're: re: re: re: status?',
  'the client is asking', 'the boss is asking',
  'is this still in progress?', 'just pinging again',
  'sorry to bug you but', 'not to be that guy but',
  'hey just wanted to check', 'can you confirm?',
  'is there an update on the update?',
  'we need this yesterday', 'what\'s the holdup?',
  'please respond', 'are you there?', 'hello?',
  '???', 'ping', 'ping ping ping',
  'hey', 'hey hey', 'yo', 'URGENT',
  'time-sensitive', 'action required', 'immediate attention',
  'drop everything', 'all hands on deck',
  'are you available?', 'can you look at this real quick?',
  'it\'ll only take 5 minutes', 'one more thing',
  'sorry one more', 'actually wait',
  'never mind found it', 'wait no I didn\'t',
  'you\'re on mute', 'can you see my screen?',
  'I\'ll go ahead and mark you as owner',
  'assigning this to you', 'looping you in',
  'adding you to the thread', 'tagging you in',
  'FYI', 'FYI (action required)',
  'thoughts?', 'feedback?', 'concerns?',
  'thumbs up?', 'approved?', 'sign-off?',
  'can we ship today?', 'is it ready?',
  'did you finish?', 'did anyone look at this?',
  'the deadline was yesterday', 'meeting about the meeting',
  'can you send me a recap?', 'can you put that in writing?',
  'who approved this?', 'where\'s the document?',
  'can you present this tomorrow?', 'I need a deck by EOD',
  'can you redo this?', 'small change', 'tiny ask',
  'one last thing', 'actually two more things',
  'this shouldn\'t take long', 'just a heads up',
  'wanted to flag this', 'raising a concern',
  'can you take the lead on this?',
  'volunteering you for this', 'you seem less busy',
  'can you own the follow-up?', 'per our conversation',
  'as discussed', 'as previously mentioned',
  'see attached', 'see below', 'see above',
  'thoughts by EOD?', 'thoughts by COB?',
  'need alignment', 'need buy-in', 'need sign-off',
  'who\'s accountable?', 'who\'s responsible?',
  'can someone take notes?', 'can you take notes?',
  'sending a calendar invite now', 'check your calendar',
  'moved the meeting up', 'pushed the meeting back',
  'double-booked', 'can you reschedule?',
  'we should discuss', 'let\'s table this',
  'let\'s parking-lot that', 'let\'s take this offline',
  'can we align on next steps?', 'action items?',
]

// ── TIER 2: OPS (normal) ── Corporate machinery. The system. ──
const ops: string[] = [
  'cross-functional alignment', 'stakeholder engagement',
  'quarterly review', 'annual planning', 'budget cycle',
  'headcount request', 'hiring freeze', 'reorg',
  'synergy', 'leverage', 'bandwidth', 'capacity planning',
  'deliverable', 'milestone', 'dependency', 'blocker',
  'escalation path', 'decision matrix', 'approval chain',
  'org chart', 'RACI matrix', 'swim lanes',
  'process improvement', 'change management', 'risk register',
  'status report', 'weekly sync', 'daily standup',
  'all-hands meeting', 'town hall', 'skip-level',
  'performance review', 'self-assessment', 'peer feedback',
  'goal setting', 'OKRs', 'KPIs', 'North Star metric',
  'pulse survey', 'engagement score', 'culture committee',
  'mission statement', 'core values', 'guiding principles',
  'strategic initiative', 'transformation program',
  'digital transformation', 'innovation lab',
  'center of excellence', 'best practice',
  'thought leadership', 'paradigm shift',
  'low-hanging fruit', 'quick win', 'big bet',
  'net new', 'greenfield', 'brownfield',
  'single source of truth', 'golden record',
  'operationalize', 'productize', 'solutionize',
  'customer-centric', 'data-driven',
  'proactive not reactive', 'fail fast',
  'move the needle', 'boil the ocean',
  'right-size', 'sunset', 'deprecate',
  'onboarding', 'offboarding', 'knowledge transfer',
  'bus factor', 'tribal knowledge', 'institutional memory',
  'scope creep', 'feature creep', 'requirement drift',
  'project charter', 'statement of work', 'scope document',
  'timeline', 'roadmap', 'Gantt chart', 'burndown chart',
  'velocity', 'throughput', 'cycle time', 'lead time',
  'sprint planning', 'retrospective', 'backlog grooming',
  'standup', 'retro', 'demo day', 'show and tell',
  'agile', 'waterfall', 'hybrid', 'scrumban',
  'Jira', 'Confluence', 'Slack', 'Teams',
  'Notion', 'Google Docs', 'shared drive',
  'version control', 'approval workflow',
  'compliance', 'audit', 'governance',
  'vendor management', 'contract negotiation',
  'budget allocation', 'cost center',
  'revenue target', 'pipeline coverage',
  'customer satisfaction', 'NPS score',
  'churn rate', 'retention metric',
  'executive summary', 'board deck',
  'investor update', 'earnings call',
  'press release', 'internal memo',
  'crisis communication', 'incident report',
  'postmortem', 'lessons learned',
  'root cause analysis', 'five whys',
  'process documentation', 'runbook',
  'training module', 'certification',
  'mandatory training overdue',
]

// ── TIER 3: VIBE (small) ── Workplace existentialism. The mood. ──
const vibe: string[] = [
  'this meeting could have been an email',
  'the email could have been nothing',
  'meeting about the meeting about the meeting',
  'blocked by: everything', 'ETA: soon\u2122',
  'the vibes are off', 'quiet quitting',
  'act your wage', 'doing my best',
  'nobody reads this', 'nobody owns this',
  'the person who built this left',
  'we\'ve always done it this way',
  'that\'s above my pay grade',
  'not my department', 'sounds like a you problem',
  'I was told there would be snacks',
  'the WiFi is down again', 'printer says no',
  'reply all apocalypse', 'CC: the entire company',
  'out of office until further notice',
  'working from home (allegedly)',
  'camera off vibes', 'you\'re still on mute',
  'I have a hard stop', 'let\'s be mindful of time',
  'we\'re over time but one more thing',
  'who scheduled this at 4:30 on a Friday',
  'mandatory fun', 'team building exercise',
  'pizza doesn\'t fix this', 'bring your own morale',
  'the org chart is a suggestion',
  'the process is the process',
  'we don\'t have a process for that',
  'we need a process for the process',
  'approved by nobody', 'rejected for unclear reasons',
  'pending since January', 'lost in approvals',
  'signed off by someone who left',
  'the doc is in someone\'s personal drive',
  'which Slack channel was that in?',
  'check the thread from three weeks ago',
  'I think we discussed this already',
  'didn\'t we decide this last quarter?',
  'the decision was made without us',
  'voluntary mandatory', 'optional (but mandatory)',
  'flexible (non-negotiable)', 'casual (formal)',
  'open door policy (door is closed)',
  'flat hierarchy (five approval layers)',
  'move fast and break things (don\'t break anything)',
  'fail fast (don\'t fail)', 'be bold (get approval first)',
  'think outside the box (stay in the box)',
  'we value your feedback (we do not)',
  'your voice matters (it does not)',
  'culture fit', 'not a culture fit',
  'growth opportunity', 'learning experience',
  'stretch assignment', 'career development',
  'development plan', 'pip', 'performance improvement',
  'lateral move', 'role consolidation',
  'strategic restructuring', 'right-sizing',
  'doing more with less', 'lean operations',
  'synergy capture', 'alignment exercise',
  'paradigm shift incoming',
  'disruption imminent', 'pivot pending',
  'circling back forever', 'perpetual follow-up',
  'lost in the shuffle', 'fell through the cracks',
  'on the back burner', 'deprioritized indefinitely',
  'archived', 'sunset delayed', 'postponed until Q never',
  'the roadmap to the roadmap', 'planning the planning',
  'pre-meeting for the meeting', 'debrief of the debrief',
  'successful failure', 'productive struggle',
  'constructive ambiguity', 'strategic patience',
  'cautiously optimistic', 'guardedly hopeful',
  'directionally correct', 'directionally wrong but committed',
  'we\'ll revisit', 'to be continued', 'noted',
  'taken under advisement', 'duly noted (ignored)',
  'parking lot', 'backlog', 'ice box',
  'long-term vision (no plan)',
  'in flight', 'in review', 'in limbo',
  'technically on track', 'on track (by some definition)',
  'green status (everything is on fire)',
  'the spreadsheet has feelings',
  'death by a thousand status updates',
  'I\'ll follow up (I will not follow up)',
  'great question (I have no answer)',
  'let me get back to you (I won\'t)',
]

// ── Build the final keyword list with size overrides ──
export const ALL_KEYWORDS: KeywordDef[] = [
  ...nags.map(text => ({ text, category: 'infra' as const, size: 'large' as const })),
  ...ops.map(text => ({ text, category: 'culture' as const, size: 'normal' as const })),
  ...vibe.map(text => ({ text, category: 'despair' as const, size: 'small' as const })),
  // Easter egg — smallest, dimmest, hardest to find
  { text: 'Hi Alex', category: 'despair' as const, size: 'small' as const },
]

// Priority quotes appear 3x for higher rotation weight
const PRIORITY_QUOTES: string[] = [
  "hey we're all on the call waiting for you",
  "Did you finish the thing? The thing from the email. The important one.",
  "It's a simple change, why is it taking so long?",
  "We still need someone to review this so hurry up",
  "This is the single most overdue item on the entire board. Please finish it. Ideally right now. Yes it's important. No it can't wait.",
  "Did you update the status?",
  "Please clean up after yourself. The shared drive is not a landfill. Though looking at it, I see how you'd get confused.",
  "I'd ask you to take better notes, but we both know you'd just lose those too.",
  "Oh look, another thing sent without context or a deadline. Keep up the good work.",
  "Whatever you're doing, please stop. The timeline is already weeping.",
  "Reminder: update your status before the sync. Not during. Not after. Before.",
  "You are 30 days overdue for the mandatory training. At this point I assume you're protesting it.",
  "Let's 'circle back' to why you thought starting something new on a Friday at 4:30 PM was a good idea.",
  "Let's 'take this offline,' preferably somewhere your chaos can't hurt anyone else.",
]

export const QUOTES: string[] = [
  // Priority quotes repeated for weight
  ...PRIORITY_QUOTES,
  ...PRIORITY_QUOTES,
  ...PRIORITY_QUOTES,
  // Regular rotation
  "hey so are you close or",
  "not to be that guy but the client is asking again",
  "we're all on the call waiting. can you join?",
  "just checking in. no pressure. but also there's pressure.",
  "someone asked me to ask you. I'm just the messenger.",
  "quick one -- is this happening today or should I update the timeline again",
  "no rush but the boss just joined the meeting",
  "can you mass-reply 'we're on track' for me? thanks.",
  "hey the whole board is red. like, all of it.",
  "so the deadline was yesterday. just fyi.",
  "I told them two more days. that was five days ago.",
  "you're still marked as 'in progress' from Q1",
  "the meeting is in ten minutes and we have nothing to show",
  "legal wants to know if we finished the thing. yes, legal.",
  "everything is broken. unrelated but also are you done",
  "the new hire finished their project before us. the new hire.",
  "I don't want to say 'per my last email' but per my last email",
  "our status page says 'on track' which is technically a lie",
  "the progress chart is going backwards. that's the wrong direction.",
  "hey no worries but the client demo is in 45 minutes",
  "can you at least change the status so it looks like progress",
  "we renamed the project phase to buy time. it didn't work.",
  "someone asked if we have a process. I laughed.",
  "this request has been open so long it has conflicts with itself",
  "they found 14 problems. in the first page. just the first page.",
  "they want to 'pivot the plan.' we haven't finished the plan.",
  "they promoted the person who caused the problem. just so you know.",
  "the project timeline is abstract art at this point",
  "honestly who even checks the status page",
  "I've been typing 'we're almost there' for six weeks now",
  "the meeting lasted 47 minutes. forty. seven. minutes.",
  "someone said 'let's take this offline' about something already offline",
  "hey remember that thing from the kickoff? yeah me neither",
  "management is 'cautiously optimistic.' I'm just cautious.",
  "we have three urgent items, five important ones, and a partridge in a pear tree",
  "the person covering this quit. mid-crisis.",
  "our process has a process for the process",
  "I stopped asking for timelines. now I just ask for vibes.",
  "the action items from the last review are now their own project",
  "we're three people deep into a whiteboard session about a font choice",
  "look I just need a yes or no. in the next hour. please.",
  "we're one 'quick change' away from missing another deadline",
  "it works if you don't check. which is how we've been doing it.",
  "the workaround for the workaround has a workaround",
  "can you fix the fix? the first fix made it worse.",
  "honestly at this point just send it. yolo.",
  "we're not behind schedule. the schedule is ahead of us.",
  "is this stuck or are you just thinking about it really hard",
  "your status says active but your output says otherwise",
  "your last update was eleven days ago. must've been a big one.",
  "we told the client it's being reviewed. we don't have reviewers.",
  "the status is green. wait no. wait. no it's red again.",
  "we have twelve versions of almost-the-same document",
  "we reorganized to move faster and now we have 47 problems",
  "just mass-update everything to 'in review.' buy us a week.",
  "hey can you respond to the thread from nine days ago. the one marked urgent.",
  "our success rate is 99.9% if you don't count the failures",
  "someone shared the confidential doc with the wrong group again",
  "the only documentation is a chat message from 2023",
  "I have a meeting about why we have too many meetings. wish me luck.",
  "Hi, just wanted to follow up on my follow-up to the follow-up.",
]

